"""Add goals and reminders to user and tasks

Revision ID: 1f357a01d347
Revises: 3c9a57facfc6
Create Date: 2026-03-02 18:46:23.681517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f357a01d347'
down_revision: Union[str, None] = '3c9a57facfc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_logs', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('task_logs', sa.Column('reminder_sent', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('daily_calorie_goal', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('daily_protein_goal', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('daily_water_goal', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('email_notifications_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_notifications_enabled')
    op.drop_column('users', 'daily_water_goal')
    op.drop_column('users', 'daily_protein_goal')
    op.drop_column('users', 'daily_calorie_goal')
    op.drop_column('task_logs', 'reminder_sent')
    op.drop_column('task_logs', 'deadline')
    # ### end Alembic commands ###
