"""Add tag and unique constraint to task_logs

Revision ID: 9bf189248808
Revises: 3d2611f06dde
Create Date: 2026-02-28 18:23:12.778156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bf189248808'
down_revision: Union[str, None] = '3d2611f06dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_logs', sa.Column('tag', sa.String(length=100), nullable=True))
    op.create_unique_constraint('uix_user_task_created', 'task_logs', ['user_id', 'task_name', 'created_at'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_task_created', 'task_logs', type_='unique')
    op.drop_column('task_logs', 'tag')
    # ### end Alembic commands ###
