"""Add indexes for telemetry querying

Revision ID: d83b4b76be93
Revises: 9bf189248808
Create Date: 2026-02-28 19:01:26.434483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd83b4b76be93'
down_revision: Union[str, None] = '9bf189248808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_health_logs_user_id'), 'health_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_task_logs_status'), 'task_logs', ['status'], unique=False)
    op.create_index(op.f('ix_task_logs_tag'), 'task_logs', ['tag'], unique=False)
    op.create_index(op.f('ix_task_logs_user_id'), 'task_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_logs_user_id'), table_name='task_logs')
    op.drop_index(op.f('ix_task_logs_tag'), table_name='task_logs')
    op.drop_index(op.f('ix_task_logs_status'), table_name='task_logs')
    op.drop_index(op.f('ix_health_logs_user_id'), table_name='health_logs')
    # ### end Alembic commands ###
